import { FaArrowRight, FaGithub } from 'react-icons/fa';

const projects = [
  { name: 'Context Bot', status: 'AI system', problem: 'Create a conversational interface grounded in user-provided knowledge.', solution: 'A RAG application that uploads and indexes PDFs, CSVs, text files, and websites for context-aware chat.', engineering: 'Uses OpenAI for LLM integration, Qdrant for vector storage, and LangChain to support retrieval and context management.', tech: 'Next.js · OpenAI · Qdrant · LangChain', github: null, demo: 'https://youtu.be/Zi-qxFximXI' },
  { name: 'Ghar Nishchit', status: 'Team product', problem: 'Make rental workflows more accessible for tenants and small landlords.', solution: 'A full-stack rental platform spanning property management, payments, contracts, maintenance, messaging, and notifications.', engineering: 'Implemented within a multi-role architecture with JWT authentication, REST APIs, MongoDB, PostgreSQL, Razorpay, and background workers.', tech: 'JWT · REST APIs · MongoDB · PostgreSQL · Razorpay', github: 'https://github.com/Soumyodeep-Dey/Ghar_Nishchit', demo: 'https://ghar-nishchit-frontend.onrender.com/' },
  { name: 'Watchly', status: 'In development', problem: 'Support a practical, discoverable e-commerce experience for watch shoppers.', solution: 'A full-stack e-commerce application with product discovery, search, sorting, filtering, and infinite scrolling.', engineering: 'Explores recommendation workflows while focusing on the API and user-flow decisions behind catalog browsing.', tech: 'React · E-commerce workflows · APIs', github: 'https://github.com/Soumyodeep-Dey/Watchly', demo: 'https://watchly-frontend.onrender.com/' },
  { name: 'BeautyMatch', status: 'Chrome Web Store', problem: 'Help shoppers evaluate beauty products without creating a tracking profile.', solution: 'A browser extension that evaluates suitability by skin tone, type, and allergies on supported storefronts.', engineering: 'Runs locally with no tracking or data sharing—a deliberate privacy decision for a user-facing product.', tech: 'React · Tailwind · CRXJS', github: 'https://github.com/Soumyodeep-Dey/BeautyMatch', demo: 'https://chromewebstore.google.com/detail/beautymatch/kongfkfcoganehdeiiaffpmmedmkbjho' },
  { name: 'Persona AI', status: 'AI application', problem: 'Explore how prompt and interaction design shape conversational experiences.', solution: 'An application that lets users interact with selectable creator-inspired conversational personas.', engineering: 'Connects an OpenAI-powered workflow to a simple, real-time interface with explicit persona switching.', tech: 'React · Vite · OpenAI API · Tailwind', github: 'https://github.com/Soumyodeep-Dey/persona_AI', demo: 'https://persona-ai-ebon.vercel.app/' },
];

function Projects() { return <main className="projects-page"><header className="projects-hero"><p className="eyebrow">Project archive</p><h1>Systems, workflows, and AI applications.</h1><p>Selected work framed around the problem, solution, and technical decisions—not just a technology list.</p></header><section className="projects-list" aria-label="Projects">{projects.map((project, index) => <article className="project-detail" key={project.name}><div className="project-index">0{index + 1}</div><div><p className="project-type">{project.status}</p><h2>{project.name}</h2><div className="story"><div><strong>Problem</strong><p>{project.problem}</p></div><div><strong>Solution</strong><p>{project.solution}</p></div><div><strong>Engineering</strong><p>{project.engineering}</p></div></div><p className="project-stack">{project.tech}</p><div className="project-links">{project.github && <a href={project.github} target="_blank" rel="noreferrer"><FaGithub /> Repository</a>}<a href={project.demo} target="_blank" rel="noreferrer">Live demo <FaArrowRight /></a></div></div></article>)}</section></main> }
export default Projects;
